### ISSUE TITLE
[Firefox] Clicking on shared pooled-resume link while logged in leads to login screen

### ISSUE THREAD

**Issue by evancoa** [rezqio/issues#159] opened 2019-01-26 19:19 UTC
Unverified, need to test

**Comment by fannydengdeng** [comment] 2019-01-27 01:02
GQL issue, looking into it now

**Comment by fannydengdeng** [comment] 2019-01-27 01:48
Bug has not been successfully reproduced

**Comment by dongyuzheng** [comment] 2019-01-27 22:15
I cannot reproduce it either

**Comment by iyyuan** [comment] 2019-02-04 09:14
Closing for now. Maybe my browser is just being weird.

**Closed as completed by iyyuan** 2019-02-04 09:14 UTC
Labels: bug
